[workspace]
resolver = "2"
members = [
    "fvm",
    "sdk",
    "shared",
    "ipld/*",
]

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true
